name: Deploy Application Image

on:
  workflow_dispatch:
    inputs:
      applicationRepository:
        description: Application Repository
        required: true
        default: 'thuf/test-xsjs'
      applicationReleaseVersion:
        description: Application Release Version
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kube Config File
        run: |
          mkdir $HOME/.kube
          echo "${{ secrets.KYMA_CONFIG }}" >> $HOME/.kube/config
          find $HOME/.kube/config -type f -exec sed -i ''s/#{KYMA_CERTIFICATE}#/${{ secrets.KYMA_CERTIFICATE }}/g'' {} \;
          find $HOME/.kube/config -type f -exec sed -i ''s/#{KYMA_SERVER}#/${{ secrets.KYMA_SERVER }}/g'' {} \;
          find $HOME/.kube/config -type f -exec sed -i ''s/#{KYMA_TOKEN}#/${{ secrets.KYMA_TOKEN }}/g'' {} \;
          export KYMA_API_SERVER=${{ secrets.KYMA_SERVER }}
          echo "KYMA_HOST=${KYMA_API_SERVER:12}" >> $GITHUB_ENV
      - name: Helm Upgrade Application Instance
        run: |
          helm repo add xsk https://www.xsk.io
          helm repo update
          helm upgrade --install xsk xsk/xsk \
          --set kyma.enabled=true \
          --set kyma.host=$KYMA_HOST \
          --set hana.enabled=true \
          --set hana.url='${{ secrets.HANA_URL }}' \
          --set hana.username=${{ secrets.HANA_USERNAME }} \
          --set hana.password='${{ secrets.HANA_PASSWORD }}' \
          --set persistentVolumeClaim.enabled=false \
          --set deployment.strategyType=RollingUpdate \
          --set application.image=${{ github.event.inputs.applicationRepository }}:${{ github.event.inputs.applicationReleaseVersion }}
