name: Deploy Application Image

on:
  workflow_dispatch:
    inputs:
      applicationRepository:
        description: Application Repository
        required: true
        default: 'thuf/test-xsjs'
      applicationReleaseVersion:
        description: Application Release Version
        required: true
      kymaAccessToken:
        description: Kyma Access Token

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kube Config File
        run: |
          mkdir $HOME/.kube
          KUBE_CONFIG=$(cat << EOF
          apiVersion: v1
          kind: Config
          current-context: xsk
          clusters:
          - name: xsk
            cluster:
              certificate-authority-data: $KYMA_CERTIFICATE
              server: $KYMA_SERVER
          contexts:
          - name: xsk
            context:
              cluster: xsk
              user: xsk
          users:
          - name: xsk
            user:
              token: $KYMA_TOKEN
          EOF
          )
          echo KUBE_CONFIG >> $HOME/.kube/config
          echo KUBE_CONFIG
          echo ${$KYMA_SERVER:12}
      - name: Helm Upgrade Application Instance
        run: |
          helm repo add xsk https://www.xsk.io
          helm repo update
          helm upgrade --install xsk xsk/xsk \
          --set kyma.enabled=true \
          --set kyma.host=${{ secrets.KYMA_HOST }} \
          --set hana.enabled=true \
          --set hana.url='${{ secrets.HANA_URL }}' \
          --set hana.username=${{ secrets.HANA_USERNAME }} \
          --set hana.password='${{ secrets.HANA_PASSWORD }}' \
          --set persistentVolumeClaim.enabled=false \
          --set deployment.strategyType=RollingUpdate \
          --set application.image=${{ github.event.inputs.applicationRepository }}:${{ github.event.inputs.applicationReleaseVersion }}
