name: Release Docker Image

on:
  workflow_dispatch:
    inputs:
      xskVersion:
        description: XSK Version
        required: true
        default: 'dirigiblelabs/xsk-kyma:latest'
      applicationReleaseVersion:
        description: Application Release Version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker Login
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} ${{secrets.DOCKER_REGISTRY}}
      - name: Build Dockerfile
        run: |
          DOCKERFILE_CONTENT=$(cat << EOF
          FROM ${{ github.event.inputs.xskVersion }}
          ADD . /usr/local/tomcat/target/dirigible/repository/root/registry/public/
          EOF
          )
          echo "$DOCKERFILE_CONTENT" >> Dockerfile
      - name: Build image with XSK
        run: |
          docker build . -t ${{ github.event.inputs.applicationReleaseVersion }}
          docker push ${{ github.event.inputs.applicationReleaseVersion }}

