name: Release Docker Image

on:
  workflow_dispatch:
    inputs:
      xskVersion:
        description: XSK Version
        required: true
        default: 'dirigiblelabs/xsk-kyma:latest'
      applicationReleaseVersion:
        description: Application Release Version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker Login
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} ${{secrets.DOCKER_REGISTRY}}
      - name: Build image with XSK
        run: |
          BASEIMAGE=${{ github.event.inputs.xskVersion }}
          REGISTRY_PATH=/usr/local/tomcat/target/dirigible/repository/root/registry/public/
          DOCKERREF=${{secrets.DOCKER_REGISTRY}}/${{ github.event.inputs.applicationReleaseVersion }}

          echo -e "FROM $BASEIMAGE\nADD . $REGISTRY_PATH" | docker build . -f - -t $DOCKERREF
          docker push $DOCKERREF

