name: Release Docker Image

on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        required: true
        description: Release Type
        options: 
        - Image Only
        - Image + Release Notes
        - Image + Release Notes + Kyma Update
      xskVersion:
        description: XSK Version
        required: true
        default: 'dirigiblelabs/xsk-kyma:latest'
      applicationRepository:
        description: Application Repository
        required: true
        default: 'thuf/test-xsjs'
      applicationReleaseVersion:
        description: Application Release Version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Release Input Parameters
        run: |
          echo "Release Type: ${{ github.event.inputs.releaseType }}"
          echo "Application Repository: ${{ github.event.inputs.applicationRepository }}"
          echo "Application Release Version: ${{ github.event.inputs.applicationReleaseVersion }}"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Dockerfile
        run: |
          DOCKERFILE_CONTENT=$(cat << EOF
          FROM ${{ github.event.inputs.xskVersion }}
          ADD . /usr/local/tomcat/target/dirigible/repository/root/registry/public/
          EOF
          )
          echo "$DOCKERFILE_CONTENT" >> Dockerfile
          echo "$DOCKERFILE_CONTENT"
      - name: Docker Login
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} ${{secrets.DOCKER_REGISTRY}}
      - name: Build Application Image
        run: |
          docker build . -t ${{ github.event.inputs.applicationRepository }}:${{ github.event.inputs.applicationReleaseVersion }}
          docker push ${{ github.event.inputs.applicationRepository }}:${{ github.event.inputs.applicationReleaseVersion }}

      - name: Create Release
        if: ${{ github.event.inputs.releaseType == 'Image + Release Notes'}} || ${{ github.event.inputs.releaseType == 'Image + Release Notes + Kyma Update'}}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.applicationReleaseVersion }}
          release_name: ${{ github.event.inputs.applicationReleaseVersion }}
          draft: false
          prerelease: false
          body: |
            ## Application Image - ${{ github.event.inputs.applicationReleaseVersion }}
            #### Docker images:
              - [${{ github.event.inputs.applicationRepository }}](https://hub.docker.com/r/${{ github.event.inputs.applicationRepository }}/tags?page=1&ordering=last_updated) - Application Image
